/**
 * Shared types for the map domain and its features. Zero runtime — data shape only,
 * in four groups: level/layer config · feature data · interaction state · label/title.
 */

// --- Nível / config de camada ---------------------------------------------

/** `bairro` é o nível das unidades (bairros e distritos), separadas por `tipo`. */
export type LevelId = 'bairro' | 'loteamento' | 'setor';

/** Color token name (`--bairro` | `--loteamento` | `--setor` | `--uncertain`) that this layer reads at runtime. */
export type ColorToken = 'bairro' | 'loteamento' | 'setor';

export interface LevelConfig {
  id: LevelId;
  label: string;
  url: string;
  sourceId: string;
  fillLayerId: string;
  lineLayerId: string;
  colorToken: ColorToken;

  /** Stroke widths: default / hover / preview (search result). */
  lineWidth: number;
  lineWidthHover: number;
  lineWidthPreview: number;
  
  /** Fixed dash pattern for this layer (e.g., setor `[2, 3]`). Absent = solid stroke. */
  dashArray?: [number, number];
}

export interface LayerToggles {
  bairro: boolean;
  loteamento: boolean;
  setor: boolean;
}

// --- Dado de feature (esquema do ETL: dados/etl/model/hierarquia_dados.md) ---

/** Bloco de contagens por categoria; `null` = sigilo do IBGE (ver `contem_sigilo`). */
export type Contagens = Record<string, number | null>;

/** Blocos censitários comuns a bairro/distrito (contagem) e loteamento (estimativa). */
export interface BlocosCenso {
  demografia: { pop: number | null; homens: number | null; mulheres: number | null; idade: Contagens };
  domicilios: {
    total: number | null;
    particulares: number | null;
    coletivos: number | null;
    ocupados: number | null;
    uso_ocasional: number | null;
    vagos: number | null;
    media_moradores: number | null;
    pct_imputados: number | null;
    tipo: Contagens;
  };
  saneamento: Record<'agua' | 'agua_canalizada' | 'banheiro' | 'esgoto' | 'lixo', Contagens>;
  alfabetizacao: { alfabetizados_15_mais: number | null; nao_alfabetizados_15_mais: number | null };
  renda_responsavel: { responsaveis: number | null; moradores: number | null; rendimento_medio: number | null };
}

/** Escolas por rede e porte (faixa de matrículas). */
export type Escolas = Record<'publicas' | 'particulares', Record<string, number>>;

/** Bairro ou distrito (`bairros_e_distritos.geojson`). */
export interface UnidadeProperties extends BlocosCenso {
  cd_unidade: string;
  nome: string;
  tipo: 'bairro' | 'distrito';
  situacao: string;
  area_km2: number;
  area_domiciliada_km2: number | null;
  enderecos_cnefe: Record<string, number>;
  escolas: Escolas;
  contem_sigilo: string[];
}

export interface LoteamentoProperties {
  cd_loteamento: string;
  nome: string;
  area_km2: number;
  cd_bairro: string;
  nm_bairro: string;
  /** `false` = limites aproximados (hachura/tracejado no mapa). */
  is_reliable: boolean;
  /** Blocos censitários alocados dos setores pelos endereços do CNEFE; `null` sem endereço. */
  estimativas: ({ metodo: string } & BlocosCenso) | null;
  enderecos_cnefe: Record<string, number>;
  escolas: Escolas;
  /** Áreas de ponderação que cobrem o loteamento, com a fração da população em cada uma. */
  aps: { cd_ap: string; peso_pop: number }[];
  estimativas_sinteticas: Record<string, { valor: number | null; aps: string[] }> | null;
  qualidade: {
    sobreposicao_pct: number;
    enderecos_compartilhados: number;
    contem_sigilo: string[];
    pct_coord_precisas: number | null;
  };
}

/** Indicador amostral: `suprimido` (n < 30) chega com `valor: null`. */
export interface IndicadorAP {
  valor: number | null;
  n: number;
  suprimido: boolean;
}

/** Área de ponderação (`areas_ponderacao.geojson`) — só aparece na ficha do loteamento. */
export interface AreaPonderacaoProperties {
  cd_ap: string;
  nome: string;
  n_pessoas: number;
  n_domicilios: number;
  indicadores: Record<string, Record<string, IndicadorAP>>;
  fonte: string;
}

// --- Estado de interação -----------------------------------------------

export interface Selection {
  level: LevelId;
  /** Feature ID generated by MapLibre (`generateId: true`), stable across re-renders in the same session. */
  featureId: string | number;
  name: string;
  properties: Record<string, unknown>;
  /** Name of the parent bairro — present when `level === 'loteamento'`. */
  parentBairro?: string;
  /** Populated by the code that creates the selection; used by `fitBounds` — without it the map won't pan. */
  bbox?: [number, number, number, number];
}

export interface HoveredBairro {
  featureId: string | number;
  name: string;
  /** Bairro ou distrito — muda só o rótulo exibido. */
  tipo?: UnidadeProperties['tipo'];
}

/** Loteamento under the cursor. Has two sources (polygon on map and list in details panel) that converge here for identical highlighting. */
export interface HoveredLoteamento {
  featureId: string | number;
  name: string;
  parentBairro?: string;
}

/** Search result in preview (hover on dropdown) — highlights without selecting. */
export interface PreviewTarget {
  level: LevelId;
  featureId: string | number;
  name: string;
  parentBairro?: string;
  tipo?: UnidadeProperties['tipo'];
}

/** Modo de encaixe da folha (mobile): "preview" mostra uma prévia baixa, "expanded" ocupa quase a tela. */
export type SheetSnap = 'preview' | 'expanded';

// --- Label / title -------------------------------------------------------
export interface FloatingTitleState {
  crumb: string;
  main: string;
}
