/**
 * Shared types for the map domain and its features. Zero runtime — data shape only,
 * in four groups: level/layer config · feature data · interaction state · label/title.
 */

// --- Nível / config de camada ---------------------------------------------

export type LevelId = 'bairro' | 'loteamento' | 'setor';

export interface TooltipField {
  label: string;
  property: string;
  format?: (value: unknown) => string;
}

/** Color token name (`--bairro` | `--loteamento` | `--setor` | `--uncertain`) that this layer reads at runtime. */
export type ColorToken = 'bairro' | 'loteamento' | 'setor';

export interface LevelConfig {
  id: LevelId;
  label: string;
  url: string;
  sourceId: string;
  fillLayerId: string;
  lineLayerId: string;
  /** Property (array) of this feature listing parent names. Absent at root level (bairro). */
  parentsProperty?: string;
  nameProperty: string;
  tooltipFields: TooltipField[];
  colorToken: ColorToken;

  /** Stroke widths: default / hover / preview (search result). */
  lineWidth: number;
  lineWidthHover: number;
  lineWidthPreview: number;
  
  /** Fixed dash pattern for this layer (e.g., setor `[2, 3]`). Absent = solid stroke. */
  dashArray?: [number, number];
}

export interface LayerToggles {
  bairro: boolean;
  loteamento: boolean;
  setor: boolean;
}

// --- Dado de feature --------------------------------------------------------

export interface LoteamentoProperties {
  name: string;
  styleUrl?: string;
  parentBairro?: string;
  is_reliable?: boolean;
  [key: string]: unknown;
}

// --- Estado de interação -----------------------------------------------

export interface Selection {
  level: LevelId;
  /** Feature ID generated by MapLibre (`generateId: true`), stable across re-renders in the same session. */
  featureId: string | number;
  name: string;
  properties: Record<string, unknown>;
  /** Name of the parent bairro — present when `level === 'loteamento'`. */
  parentBairro?: string;
  /** Populated by the code that creates the selection; used by `fitBounds` — without it the map won't pan. */
  bbox?: [number, number, number, number];
}

export interface HoveredBairro {
  featureId: string | number;
  name: string;
}

/** Loteamento under the cursor. Has two sources (polygon on map and list in details panel) that converge here for identical highlighting. */
export interface HoveredLoteamento {
  featureId: string | number;
  name: string;
  parentBairro?: string;
}

/** Search result in preview (hover on dropdown) — highlights without selecting. */
export interface PreviewTarget {
  level: LevelId;
  featureId: string | number;
  name: string;
  parentBairro?: string;
}

// --- Label / title -------------------------------------------------------
export interface FloatingTitleState {
  crumb: string;
  main: string;
}

/** Target for the label drawn inside the geometry. Requires the polygon: anchor and size come from it. */
export interface MapLabelTarget {
  name: string;
  geometry: GeoJSON.Geometry;
  colorToken: 'bairro' | 'loteamento' | 'uncertain';
}
